/**
 * Brand geometry for Salmon Wallet.
 *
 * The mark as vector path data rather than a bitmap. Every surface draws the
 * same three paths: React Native through `react-native-svg`, the DOM through
 * an inline `<svg>`, and build scripts by writing the string out to a file for
 * store artwork.
 *
 * Path data rather than an `.svg` import on purpose — an import would depend on
 * each app configuring an SVG transformer, and the two apps do not agree on
 * one. Strings need no bundler support and cannot drift between platforms.
 *
 * The paths carry no fill. Callers supply the color, which is what makes the
 * mark tintable: salmon ink on a dark ground, `text.onAccent` on a salmon
 * fill, or a flat monochrome for a store icon. The source artwork hardcoded
 * `#FCFCFC`, which allowed exactly one of those.
 *
 * Geometry is the authored master at 253x237 — the `Icon / Salmon Head`
 * component of `salmonwallet2627.pen` (SOT), flattened to one viewBox and
 * centred on x = 126.5 so the mark mirrors about its own axis. Do not re-fit
 * it to a square.
 */

export {
  wordmarkPaths,
  wordmarkText,
  wordmarkTypeface,
  wordmarkViewBox,
  wordmarkViewBoxAttr,
} from './wordmark.generated';

import { wordmarkPaths, wordmarkViewBox, wordmarkViewBoxAttr } from './wordmark.generated';

/** Native artboard of the authored mark. */
export const markViewBox = { width: 253, height: 237 } as const;

/** `viewBox` attribute value, for both `react-native-svg` and the DOM. */
export const markViewBoxAttr = '0 0 253 237';

/** Width divided by height — use it to derive one dimension from the other. */
export const markAspectRatio = markViewBox.width / markViewBox.height;

/**
 * The three paths that compose the mark, in draw order:
 * the body (with both eyes cut out as counters), then the right and left fins.
 */
export const markPaths = [
  'M189.676 53.962C177.731 46.79 165.138 41.69 152.196 38.81L138.484 8.296C138.484 8.296 134.876 0 126.323 0C117.771 0 114.516 8.296 114.516 8.296L100.804 38.791C87.839 41.69 75.208 46.809 63.247 53.981C39.474 100.136 33.034 145.129 36.254 189.494C50.181 202.986 108.376 237 126.323 237C144.271 237 202.819 202.986 216.746 189.494C219.966 145.129 213.522 100.136 189.753 53.981L189.676 53.962ZM101.277 147.338C93.79 147.338 87.604 138.411 87.604 127.421C87.604 116.427 93.575 107.427 101.239 107.427C108.899 107.427 115.047 116.427 114.908 127.421C114.774 138.411 108.88 147.338 101.258 147.338L101.277 147.338ZM151.684 147.338C144.178 147.338 138.03 138.411 138.03 127.421C138.03 116.427 144.001 107.427 151.684 107.427C159.364 107.427 165.454 116.427 165.315 127.421C165.181 138.411 159.306 147.338 151.684 147.338Z',
  'M251.919 167.526L234.356 112.174C232.196 105.4 225.929 100.793 218.817 100.793C216.696 100.793 214.633 101.206 212.727 101.974C220.742 128.656 223.964 157.444 221.45 188.812L236.36 188.812C247.401 188.812 255.239 178.061 251.9 167.526L251.919 167.526Z',
  'M1.081 167.526L18.644 112.174C20.804 105.4 27.071 100.793 34.183 100.793C36.304 100.793 38.367 101.206 40.273 101.974C32.258 128.656 29.036 157.444 31.55 188.812L16.64 188.812C5.599 188.812 -2.239 178.061 1.1 167.526L1.081 167.526Z',
] as const;

/**
 * Serializes the mark to a standalone SVG document.
 *
 * For build scripts and store artwork. In an app, draw `markPaths` directly
 * rather than injecting this string.
 */
export const markToSvg = (fill: string, size?: number): string => {
  const width = size ?? markViewBox.width;
  const height = size ? Math.round(size / markAspectRatio) : markViewBox.height;
  const paths = markPaths.map((d) => `<path fill="${fill}" d="${d}"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="${markViewBoxAttr}">${paths}</svg>`;
};

/** Wordmark width divided by height. */
export const wordmarkAspectRatio = wordmarkViewBox.width / wordmarkViewBox.height;

/**
 * Serializes the wordmark to a standalone SVG document.
 *
 * The logotype is the interface font's own contours, not artwork: it is
 * generated by `scripts/wordmark.py` and regenerating it is how the typeface
 * changes. Like the mark, it carries no baked-in fill.
 *
 * @param fill - Ink color. The wordmark is a single color by construction.
 * @param width - Rendered width; height follows the aspect ratio.
 */
export const wordmarkToSvg = (fill: string, width?: number): string => {
  const w = width ?? wordmarkViewBox.width;
  const h = width ? Math.round(width / wordmarkAspectRatio) : wordmarkViewBox.height;
  const paths = wordmarkPaths.map((d) => `<path fill="${fill}" d="${d}"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${wordmarkViewBoxAttr}">${paths}</svg>`;
};

/**
 * Per-chain brand marks — badges, avatars, and tags that need a chain's own
 * hue rather than a depth of the water column.
 *
 * These are brand marks, not theme colours: a chain's identity color is
 * fixed by that chain's own brand, not by "Deep Water"'s ramp, so they live
 * here rather than in `semantic.ts`. Moved from `colors.palette` (2026-09-01
 * cleanup), which now re-exports these same values —
 * `apps/extension` still reads `colors.palette` directly.
 */
const chainMarkHues = {
  orange: '#FF5C45',
  green: '#10B981',
  purple: '#8B5CF6',
  amber: '#F59E0B',
  blue: '#3B82F6',
  pink: '#EC4899',
  cyan: '#06B6D4',
  indigo: '#6366F1',
} as const;

export const chainMarks = {
  ...chainMarkHues,
  /**
   * Which of the hues above each chain answers to — the one place a chain
   * name is turned into a colour, so two surfaces cannot pick different
   * ambers for Bitcoin. No new hue is minted here: Bitcoin takes `amber`,
   * Solana `purple`, Ethereum `indigo`.
   *
   * A hue is not a legibility guarantee. Whether a given surface may spend
   * one on the hint is decided in `semantic.ts` (`chain.hintInk`), per mode,
   * against that mode's own ground.
   */
  byChain: {
    bitcoin: chainMarkHues.amber,
    solana: chainMarkHues.purple,
    ethereum: chainMarkHues.indigo,
  },
} as const;

export type ChainMarks = typeof chainMarks;
