/**
 * Brand geometry for Salmon Wallet.
 *
 * The mark as vector path data rather than a bitmap. Every surface draws the
 * same three paths: React Native through `react-native-svg`, the DOM through
 * an inline `<svg>`, and build scripts by writing the string out to a file for
 * store artwork.
 *
 * Path data rather than an `.svg` import on purpose — an import would depend on
 * each app configuring an SVG transformer, and the three apps do not agree on
 * one. Strings need no bundler support and cannot drift between platforms.
 *
 * The paths carry no fill. Callers supply the color, which is what makes the
 * mark tintable: salmon ink on a dark ground, `text.onAccent` on a salmon
 * fill, or a flat monochrome for a store icon. The source artwork hardcoded
 * `#FCFCFC`, which allowed exactly one of those.
 *
 * Geometry is the authored master at 253x236; do not re-fit it to a square.
 */

export {
  wordmarkPaths,
  wordmarkText,
  wordmarkTypeface,
  wordmarkViewBox,
  wordmarkViewBoxAttr,
} from './wordmark.generated';

import { wordmarkPaths, wordmarkViewBox, wordmarkViewBoxAttr } from './wordmark.generated';

/** Native artboard of the authored mark. */
export const markViewBox = { width: 253, height: 236 } as const;

/** `viewBox` attribute value, for both `react-native-svg` and the DOM. */
export const markViewBoxAttr = '0 0 253 236';

/** Width divided by height — use it to derive one dimension from the other. */
export const markAspectRatio = markViewBox.width / markViewBox.height;

/**
 * The three paths that compose the mark, in draw order:
 * the body (with both eyes cut out as counters), then the right and left fins.
 */
export const markPaths = [
  'M189.693 54.0916C177.749 46.924 165.158 41.824 152.212 38.9491L138.501 8.4475C136.87 3.40657 132.136 0 126.793 0H126.243C120.9 0 116.165 3.42626 114.535 8.4475L100.823 38.9294C87.8582 41.824 75.2271 46.9437 63.2639 54.1113C39.4946 100.248 33.0513 145.222 36.2729 189.567C50.2006 203.055 81.081 219.733 97.641 226.33C107.345 230.189 110.311 232.139 120.035 233.754C128.679 236.195 131.291 235.25 137.911 234.561C148.107 231.843 152.35 229.087 156.475 226.862C173.997 217.784 202.835 203.075 216.763 189.586C220.534 138.153 210.3 93.592 189.693 54.0719V54.0916ZM101.295 147.428C93.8104 147.428 87.6225 138.507 87.6225 127.52C87.6225 116.532 93.5943 107.533 101.255 107.533C108.917 107.533 115.065 116.532 114.928 127.52C114.79 138.507 108.897 147.428 101.275 147.428H101.295ZM151.701 147.428C144.197 147.428 138.049 138.507 138.049 127.52C138.049 116.532 144.021 107.533 151.701 107.533C159.382 107.533 165.472 116.532 165.334 127.52C165.197 138.507 159.323 147.428 151.701 147.428Z',
  'M251.592 167.159L234.03 111.807C231.869 105.033 225.603 100.426 218.492 100.426C216.37 100.426 214.308 100.839 212.402 101.607C220.417 128.289 223.638 157.077 221.124 188.445H236.034C247.074 188.445 254.912 177.694 251.572 167.159H251.592Z',
  'M0.757632 168.203L18.3194 112.852C20.4803 106.078 26.7467 101.47 33.8579 101.47C35.9794 101.47 38.0421 101.884 39.9475 102.652C31.9328 129.333 28.7111 158.122 31.2256 189.489H16.3157C5.27577 189.489 -2.56221 178.738 0.777276 168.203H0.757632Z',
] as const;

/**
 * Serializes the mark to a standalone SVG document.
 *
 * For build scripts and store artwork. In an app, draw `markPaths` directly
 * rather than injecting this string.
 */
export const markToSvg = (fill: string, size?: number): string => {
  const width = size ?? markViewBox.width;
  const height = size ? Math.round(size / markAspectRatio) : markViewBox.height;
  const paths = markPaths.map((d) => `<path fill="${fill}" d="${d}"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="${markViewBoxAttr}">${paths}</svg>`;
};

/** Wordmark width divided by height. */
export const wordmarkAspectRatio = wordmarkViewBox.width / wordmarkViewBox.height;

/**
 * Serializes the wordmark to a standalone SVG document.
 *
 * The logotype is the interface font's own contours, not artwork: it is
 * generated by `scripts/wordmark.py` and regenerating it is how the typeface
 * changes. Like the mark, it carries no baked-in fill.
 *
 * @param fill - Ink color. The wordmark is a single color by construction.
 * @param width - Rendered width; height follows the aspect ratio.
 */
export const wordmarkToSvg = (fill: string, width?: number): string => {
  const w = width ?? wordmarkViewBox.width;
  const h = width ? Math.round(width / wordmarkAspectRatio) : wordmarkViewBox.height;
  const paths = wordmarkPaths.map((d) => `<path fill="${fill}" d="${d}"/>`).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${wordmarkViewBoxAttr}">${paths}</svg>`;
};

/**
 * Per-chain brand marks — badges, avatars, and tags that need a chain's own
 * hue rather than a depth of the water column.
 *
 * These are brand marks, not theme colours: a chain's identity color is
 * fixed by that chain's own brand, not by "Deep Water"'s ramp, so they live
 * here rather than in `semantic.ts`. Moved from `colors.palette` (2026-09-01
 * cleanup), which now re-exports these same values — `apps/web` and
 * `apps/extension` still read `colors.palette` directly.
 */
const chainMarkHues = {
  orange: '#FF5C45',
  green: '#10B981',
  purple: '#8B5CF6',
  amber: '#F59E0B',
  blue: '#3B82F6',
  pink: '#EC4899',
  cyan: '#06B6D4',
  indigo: '#6366F1',
} as const;

export const chainMarks = {
  ...chainMarkHues,
  /**
   * Which of the hues above each chain answers to — the one place a chain
   * name is turned into a colour, so two surfaces cannot pick different
   * ambers for Bitcoin. No new hue is minted here: Bitcoin takes `amber`,
   * Solana `purple`, Ethereum `indigo`.
   *
   * A hue is not a legibility guarantee. Whether a given surface may spend
   * one on the hint is decided in `semantic.ts` (`chain.hintInk`), per mode,
   * against that mode's own ground.
   */
  byChain: {
    bitcoin: chainMarkHues.amber,
    solana: chainMarkHues.purple,
    ethereum: chainMarkHues.indigo,
  },
} as const;

export type ChainMarks = typeof chainMarks;
